import pino from "pino";

import { env } from "../../config/env";

const redactedPaths = [
  "req.headers.authorization",
  "req.headers.cookie",
  "headers.authorization",
  "headers.cookie",
  "req.body.adminPassword",
  "req.body.password",
  "req.body.pass",
  "req.body.pwd",
  "req.body.token",
  "req.body.accessToken",
  "req.body.refreshToken",
  "req.body.verificationCode",
  "req.body.access_token",
  "req.body.refresh_token",
  "req.body.tokens.*",
  "req.body.credentials.*",
  "req.query.token",
  "req.query.accessToken",
  "req.query.refreshToken",
  "req.query.refresh_token",
  "req.query.password",
  "req.params.token",
  "refreshToken",
  "refresh_token",
  "body.refreshToken",
  "body.refresh_token",
  "query.refreshToken",
  "query.refresh_token",
  "req.body.databaseUrl",
  "req.body.database_url",
  "req.body.dbUrl",
  "req.body.db_url",
  "databaseUrl",
  "database_url",
  "dbUrl",
  "db_url",
  "config.database.url",
  "config.database.password",
  "SMTP_PASSWORD",
  "smtp.password",
  "config.smtp.password",
  "req.body.smtpPassword",
  "req.body.smtp_password",
  "smtpPassword",
  "smtp_password",
  "JWT_ACCESS_SECRET",
  "JWT_REFRESH_SECRET",
  "jwtAccessSecret",
  "jwtRefreshSecret",
  "auth.jwtAccessSecret",
  "auth.jwtRefreshSecret",
  "config.auth.jwtAccessSecret",
  "config.auth.jwtRefreshSecret",
];

export const logger = pino({
  level: env.logging.level,
  redact: {
    paths: redactedPaths,
    censor: "[REDACTED]",
  },
});
